VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Day"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Settimane As String
Public Monthday As String
Public particularDate As Date
Public daysCompressedInOneCol As Integer

Public stockPlant As Variant
Public grossReq As Variant
Public grossInitialReqVal As Variant
Public Soho As Variant
Public etaQty As Variant
Public delins As Variant
Public consumato As Variant
Public consegnato As Variant
Public Ebal As Variant
Public firstInsertingPosition As Boolean
Public orderComment As String
Public commentHeight As Integer
Public formula As Variant


